# Generated by Django 5.2.5 on 2026-06-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('rarity', models.CharField(max_length=30)),
                ('image_url', models.URLField(blank=True)),
                ('in_normal_stock', models.BooleanField(default=False)),
                ('in_mirage_stock', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
