# Generated by Django 5.2.5 on 2026-06-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruit',
            name='image_url',
        ),
    ]
