# Generated by Codex on 2026-07-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fruits", "0003_stock_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="stock_cycle_key",
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                fields=("user", "fruit", "stock_type", "stock_cycle_key"),
                name="unique_notification_per_stock_cycle",
            ),
        ),
    ]
